services:
  communitie-events-backend:
    build:
      context: ./../../backend
      dockerfile: Dockerfile
    container_name: communitie-events-backend
    ports:
      - "8124:8080"
    environment:
      APP_KEY: ${APP_KEY}
      APP_SAAS_MODE_ENABLED: "true"
      APP_FRONTEND_URL: ${APP_FRONTEND_URL}
      APP_CDN_URL: ${APP_CDN_URL}
      FILESYSTEM_DISK: "s3-public"
      JWT_SECRET: ${JWT_SECRET}
      LOG_CHANNEL: "stderr"
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      AWS_PUBLIC_BUCKET: ${AWS_PUBLIC_BUCKET}
      AWS_PRIVATE_BUCKET: ${AWS_PRIVATE_BUCKET}
      MAIL_MAILER: "smtp"
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      DB_CONNECTION: "pgsql"
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_USER: ${REDIS_USER}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_URL: ${REDIS_URL}
      QUEUE_CONNECTION: "redis"
      DATABASE_URL: ${DATABASE_URL}
