services:
  communitie-events-frontend:
    build:
      context: ./../../frontend
      dockerfile: Dockerfile.ssr
    container_name: communitie-events-frontend
    ports:
      - "8125:5678"
    environment:
      VITE_API_URL_SERVER: "http://172.19.0.2:8080"
      VITE_API_URL_CLIENT: "http://172.19.0.2:8080"
      VITE_FRONTEND_URL: "http://localhost:5678"
    